### ISSUE TITLE
cannot save options

### ISSUE THREAD

**Issue by vmdsb** [def00111/yahoo-mail-notifier#1]
the save button is always disabled
![20200221122525](https://user-images.githubusercontent.com/13284242/75034540-4f00a200-54a5-11ea-8567-78c1dcfb06a6.jpg)

**Comment by def00111** [comment]
This is fixed in new version 1.2.2 (needs review)

**Comment by vmdsb** [comment]
but that update isn't available for download yet. In chrome store the version is 1.2.1
![20200221130209](https://user-images.githubusercontent.com/13284242/75036755-81f96480-54aa-11ea-9172-0096a6b3e147.jpg)

**Comment by def00111** [comment]
It's needs some time, before the add-on is reviewed and published (2-3 days)

**Comment by vmdsb** [comment]
thanks for quickly responding.
btw, I hope it will have right-corner popup, such as https://chrome.google.com/webstore/detail/x-notifier-for-gmailhotma/cdfjbkbddpfnoplfhceolpopfoepleco
on the other hand, I don't feel so safe by typing my password into that https://chrome.google.com/webstore/detail/x-notifier-for-gmailhotma/cdfjbkbddpfnoplfhceolpopfoepleco
Meanwhile, I'll disable your extension, and will be using https://chrome.google.com/webstore/detail/x-notifier-for-gmailhotma/cdfjbkbddpfnoplfhceolpopfoepleco
Thank you so much and keep on the good work!

**Comment by def00111** [comment]
You don't need to type your password into my add-on!
I was thinking all the time, to add a mail preview popup window like this one:
https://addons.mozilla.org/firefox/addon/gmx-mailcheck/

**Comment by vmdsb** [comment]
That's good news! I will be waiting for the update and might volunteer to provide you testing feedback . Thanks!

**Comment by vmdsb** [comment]
Today I was able to update the extension successfully to 1.2.2. It took a minute or so and I updated it manually. Now the save button isn't disabled. The button works. Let's see how it notifies in the next few days. Thanks.
