### ISSUE TITLE
clicking doesn't close notification / doesn't open if chrome is running in background

### ISSUE THREAD

**Issue by vmdsb** [def00111/yahoo-mail-notifier#2]
Hi,
Thanks this extension which I'm using.
It is reliable and works very well in terms of notifying new messages and clicking opens the Yahoo inbox in Chrome. 
However it doesn't open Yahoo inbox if Chrome is running in background.

Furthermore, it doesn't close it's notification popup when I click on it.
Thanks,
v

**Comment by def00111** [comment]
>  However it doesn't open Yahoo inbox if Chrome is running in background.

I don't know what you mean.
I'm not using Chrome that much.

**Comment by vmdsb** [comment]
I'm using a extension named "trayEnabler" which keeps Chrome running in the background even when all the windows and tabs are closed. The purpose is to make it faster to open a Chrome window. So, when all windows are closed the background process is able to display the notification popup, however it doesn't open a Chrome window when it is clicked. On the other hand, when one (or more) chrome windows exist, the popup notification is able to open a Chrome window when it is clicked. Do you understand? Sorry, I'm portuguese, and my english is very basic.

**Comment by vmdsb** [comment]
https://chrome.google.com/webstore/detail/trayenabler/pmngpbahkehcgeppngnbnfbmmdclkddj

**Comment by vmdsb** [comment]
I think this should be possible because all the sites that send push notifications to Chrome, such as Facebook notifications, news notifications, are able to open a chrome window, even if all chrome windows are closed, and chrome is only running invisibly in the background. So, it might be a permissions settings issue? I can't find out.

**Comment by def00111** [comment]
Can you test the [add-on](https://github.com/def00111/yahoo-mail-notifier/files/4302578/background.zip)?

**Comment by def00111** [comment]
But it should work now.

**Comment by def00111** [comment]
I have also included the "background" permission.

**Comment by def00111** [comment]
> clicking doesn't close notification

Clicking on the notification closes it (atleast for me).
Or what you mean exactly?

**Comment by vmdsb** [comment]
It doesn't work for me. I tested it just now. I clicked on your yahoo notification popup, it opened Yahoo mail tab, (because there existed a chrome window), however the popup remained, and I had to explicitly close it in the [x] button.This issue might be my fault, I mean, it might be caused by some conflict with another installed extension. You see, I have about 45 enabled extensions and more than 100 disabled but installed. Anyway, Facebook notifications works perfectly: they disappear while clicking and they open their window even when there is no chrome window, as long as there is a chrome background process. Sorry.
    On Saturday, 7 March 2020, 22:56:22 WET, def00111 <notifications@github.com> wrote:  
 
 

clicking doesn't close notification


Clicking on the notification closes it (atleast for me).
Or what you mean exactly?

**Comment by vmdsb** [comment]
Ok, I downloaded it but I don't know how to install/use it.
    On Saturday, 7 March 2020, 22:22:26 WET, def00111 <notifications@github.com> wrote:  
 
 
Can you test the add-on?

**Comment by def00111** [comment]
> It doesn't work for me.

Sorry, i can not help you then. It is working for me.
I don't know what problem you have.

**Comment by def00111** [comment]
Did you disabled the other "Yahoo! Mail Notifier" extension before testing the new version?

**Comment by def00111** [comment]
![chrome_2jS9ExdT5e](https://user-images.githubusercontent.com/10849366/76158742-654f6480-6119-11ea-961c-426367b09404.png)

You load the extension from here?

**Comment by def00111** [comment]
Can you test it with other extensions disabled?

**Comment by vmdsb** [comment]
1) "Sorry, i can not help you then. It is working for me. I don't know what problem you have."never mind
2) "Did you disabled the other "Yahoo! Mail Notifier"extension before testing the new version?"Yes, since your notifier is reliable notifying, although the popup can't open chrome when no window exists.
3) "You load the extension from here?"I couldn't use your link, so installed it from chrome webstore.
4) "Can you test it with other extensions disabled?"Yes, that would be a tedious time consuming task, because I have dozens active extensions and even more installed that I would waste a lot of time and hardly remember exactly which extensions were enabled.To aliviate this hard work I installed this extension manager: https://chrome.google.com/webstore/detail/extension-manager/bfmjiakdfoacijccjgkkhoepjklhohle/related?hl=enAfter installing, I disabled all extensions except for yours.Then I put a fake unread message in the inbox.No notification was shown because your extension requires at least one existing chrome window.As soon as I launched chrome, it worked correctly, obviously.My second test was with "trayEnabler" enabled, so to let a chrome process running in the background even when no window exists.The result? Yes the notification appeared, however, clicking on it couldn't open the window, because there was no chrome window, just the invisible chrome background process. After I manually opened a blank chrome window, and then I clicked your notification, yes it worked. Anyway, after the clickon your notification, the Yahoo site appeared but that notification didn't disappear.



    On Sunday, 8 March 2020, 08:01:51 WET, def00111 <notifications@github.com> wrote:  
 
 
Can you test it with other extensions disabled?

**Comment by def00111** [comment]
> 3) "You load the extension from here?"I couldn't use your link, so installed it from chrome webstore.

But chrome webstore has old version. You didn't test https://github.com/def00111/yahoo-mail-notifier/files/4302578/background.zip?

**Comment by def00111** [comment]
I will upload new version to chrome webstore anyway.

**Comment by vmdsb** [comment]
No, I couldn't install because I don't know how to install a extension from files, I only know how to install directly from Google Chrome's webstore. Can you tell me how to install a extension from your downloaded files?
    On Monday, 9 March 2020, 12:18:03 WET, def00111 <notifications@github.com> wrote:  
 
 
   
   - "You load the extension from here?"I couldn't use your link, so installed it from chrome webstore.


But chrome webstore has old version. You didn't test https://github.com/def00111/yahoo-mail-notifier/files/4302578/background.zip?

**Comment by vmdsb** [comment]
ok
    On Monday, 9 March 2020, 12:19:14 WET, def00111 <notifications@github.com> wrote:  
 
 
I will upload new version to chrome webstore anyway.

**Comment by def00111** [comment]
https://webkul.com/blog/how-to-install-the-unpacked-extension-in-chrome/

**Comment by vmdsb** [comment]
thanks, I'll take a look and try this afternoon.
    On Monday, 9 March 2020, 12:28:41 WET, def00111 <notifications@github.com> wrote:  
 
 
https://webkul.com/blog/how-to-install-the-unpacked-extension-in-chrome/

**Comment by def00111** [comment]
You using Windows 10? Or other os?

**Comment by vmdsb** [comment]
Windows 7 Proffessional 64Bit. I installed successfully your packed extension. I'm now testing it. Please wait...
    On Monday, 9 March 2020, 13:46:40 WET, def00111 <notifications@github.com> wrote:  
 
 
You using Windows 10? Or other os?

**Comment by def00111** [comment]
Maybe in Windows 7, the notification doesn't close when clicking?

**Comment by vmdsb** [comment]
Success: -It was able to open a chrome window even when all chrome windows were closed. (The background process was running, of course.) The notification popup didn't disappear when I clicked in the center. I had to click in the [x] to close it manually.
    On Monday, 9 March 2020, 13:46:40 WET, def00111 <notifications@github.com> wrote:  
 
 
You using Windows 10? Or other os?

**Comment by def00111** [comment]
Can you make a screenshot of the notification?
So i can look, how it looks like?

**Comment by vmdsb** [comment]
But Facebook notifications close when clicked, as well of other websites notifications. Never mind. Maybe this insignificant issue can be annoying for some people, but for me your extension is good enough for me. Thanks.
    On Monday, 9 March 2020, 14:19:41 WET, def00111 <notifications@github.com> wrote:  
 
 
Maybe in Windows 7, the notification doesn't close when clicking?

**Comment by vmdsb** [comment]
Ok, please wait.
    On Monday, 9 March 2020, 14:22:15 WET, def00111 <notifications@github.com> wrote:  
 
 
Can you make a screenshot of the notification?
So i can look, how it looks like?

**Comment by vmdsb** [comment]
On Monday, 9 March 2020, 14:22:15 WET, def00111 <notifications@github.com> wrote:  
 
 
Can you make a screenshot of the notification?
So i can look, how it looks like?

**Comment by def00111** [comment]
> Maybe in Windows 7, the notification doesn't close when clicking?

But this is not a problem.
Then i call "chrome.notifications.clear" in the onClicked handler to close the notification.

**Comment by vmdsb** [comment]
The opening problem was solved: It opens Yahoo even when no chrome window exist (as long as the chrome background process is running). Congradulations.
    On Monday, 9 March 2020, 14:26:28 WET, def00111 <notifications@github.com> wrote:  
 
 

Maybe in Windows 7, the notification doesn't close when clicking?


But this is not a problem.
Then i call "chrome.notifications.clear" in the onClicked handler to close the notification.

**Comment by def00111** [comment]
Can you test new [version](https://github.com/def00111/yahoo-mail-notifier/files/4307342/background.zip)?

**Comment by vmdsb** [comment]
ok
    On Monday, 9 March 2020, 14:56:10 WET, def00111 <notifications@github.com> wrote:  
 
 
Can you test new version?

**Comment by vmdsb** [comment]
Congratulations. It works. The problem was solved. Now, the notification _disappears_ when clicked and yahoo window opens, even without any chrome window. 
Btw, Just a small suggestion: by default "check every...minutes" should be enabled/checked upon installation, otherwise some users may be disappointed, because the notifier seems not working, because the user must go immediately to options and check the first option, otherwise it will never popup the notifications. What do you think?
On Monday, 9 March 2020, 14:56:10 WET, def00111 <notifications@github.com> wrote: 
 
 
Can you test new version?

**Comment by def00111** [comment]
Or i open the options on installation?

**Comment by vmdsb** [comment]
ok. btw, the options are not very clear for me:- I suppose "show new emails only" refers to the extension icon in the toolbar, not the popup, right? This should be stated more clear to the user.- I suppose "Notify on new emails" means "Notify _ONLY_ on new emails". Am I correct? But then it should notify old emails as well, but it doesn't, although I didn't activate that option. This is also not clear enough for me. 
    On Monday, 9 March 2020, 15:15:07 WET, def00111 <notifications@github.com> wrote:  
 
 
Or i open the options on installation?

**Comment by def00111** [comment]
> I suppose "show new emails only" refers to the extension icon in the toolbar, not the popup, right?

The "Show new emails only" option will show you the emails, that are unseen (not unread).

**Comment by def00111** [comment]
> I suppose "Notify on new emails" means "Notify _ONLY_ on new emails".

Maybe "Show notification, when new emails are found"?

**Comment by vmdsb** [comment]
<<The "Show new emails only" option will show you the emails,       that are unseen (not unread).>>
Yes, I know I can see a email without actually reading the text letters in my front, but the reading action would be impossible to detect by the extension.
So, what is the difference from "unseen" and "unread"?
Maybe you mean "unread" is equivalent to view only that message-title in inbox-list without opening that message-text? i.e. "unopened"?
While "unseen" could mean that you never saw that message-title in the inbox-list?
Thanks.

    On Monday, 9 March 2020, 19:08:12 WET, def00111 <notifications@github.com> wrote:  
 
 

I suppose "show new emails only" refers to the extension icon in the toolbar, not the popup, right?


The "Show new emails only" option will show you the emails, that are unseen (not unread).

**Comment by vmdsb** [comment]
"Notify on new emails"
What will happen if I uncheck that option? 

    On Monday, 9 March 2020, 19:17:37 WET, def00111 <notifications@github.com> wrote:  
 
 

I suppose "Notify on new emails" means "Notify ONLY on new emails".


Maybe "Show notification, when new emails are found"?

**Comment by def00111** [comment]
> "Notify on new emails"
> What will happen if I uncheck that option?

This option shows the notification, when you have new emails.
If you uncheck it, then no notification will be shown to you.

![WHGkiyJYi2](https://user-images.githubusercontent.com/10849366/76515467-e9775400-6459-11ea-974e-ceff9ac832ec.png)

How the notification looks like in Windows 10.

I'm closing this Issue now, because the reported Issues are fixed.

**Comment by vmdsb** [comment]
Thanks.  

    On Thursday, 12 March 2020, 11:16:34 WET, def00111 <notifications@github.com> wrote:  
 
 



"Notify on new emails"
What will happen if I uncheck that option?


This option shows the notification, when you have new emails.
If you uncheck it, then no notification will be shown to you.



How the notification looks like in Windows 10.

I'm closing this Issue now, because the reported Issues are fixed.
