### ISSUE TITLE
left click should also check

### ISSUE THREAD

**Issue by vmdsb** [def00111/yahoo-mail-notifier#3]
Hi, this is a very good extension and I'm using it permanently.
If you allow me to suggest an improvement I, here it goes:
The extension updates it's mail count periodically.
Sometimes, when I left click (to open mail box) the count doesn't match because it was just before it's periodic update occurred.
Of course, I can right-click and ask it to "Check Now" and obviously the mail count will then match.
However, as a matter of consistency, I suggest that the left-click should also perform the update function to prevent the mismatching of the counts.
Thanks for all,
Greetings,
Vitor

**Comment by def00111** [comment]
Fixed in newer versions.
