### ISSUE TITLE
Mail Notifier in Firefox only showing 99+ emails and not reducing as I open emails

### ISSUE THREAD

**Issue by thatcrazydoglady** [def00111/yahoo-mail-notifier#4]

**Comment by def00111** [comment]
Can you tell me how much unread emails you have?

Does the "Show new emails only" option also works for you?

Do you mean, if you open a email the `99+` should go away?

**Note:** If it shows `99+`, you can still see how much unread emails you have by moving the mouse cursor over the mail icon (to display the tooltip).

![firefox_YB5Xx7Im3t](https://user-images.githubusercontent.com/10849366/116778294-4aecee80-aa71-11eb-93bd-1b75904c3a0b.png)

**Comment by thatcrazydoglady** [comment]
Wow!  I didn't realize I could do that!  I've now changed my notifications to new mail only and that's gonna be great!
Thanks so much!

    On Saturday, May 1, 2021, 2:38:08 AM PDT, def00111 ***@***.***> wrote:  
 
 


Can you tell me how much unread emails you have?

Does the "Show new emails only" option also works for you?

Do you mean, if you open a email the 99+ should go away?

Note: If it shows 99+, you can still see how much unread emails you have by moving the mouse cursor over the mail icon (to display the tooltip).
